application: hrsfansretreat
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /admin
    static_files: static/admin.html
    upload: static/admin.html
    login: admin
    secure: always

  - url: /static/admin.js
    static_files: static/admin.js
    upload: static/admin.js
    login: admin
    secure: always

  - url: /
    static_files: static/index.html
    upload: static/index.html
    login: required
    secure: always

  - url: /static/([^/]*\.(css|js|png))
    static_files: static/\1
    upload: static/[^/]*\.(css|js|png)
    secure: always

  - url: /([^/]*\.html)
    static_files: static/\1
    upload: static/[^/]*\.html
    secure: always

  - url: /_ah/login_required
    script: main.application
    secure: always

  - url: /openid_redirect
    script: main.application
    secure: always

  - url: /authorize
    script: main.application
    secure: always

  - url: /call/admin/.*
    script: main.application
    login: admin
    secure: always

  - url: /call/[^/]*
    script: main.application
    login: required
    secure: always

skip_files:
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?\..*
  - ^(.*/)?.*\.coffee
  - ^(.*/)?.*\.md
  - ^LICENSE

libraries:
  - name: yaml
    version: "3.10"
