application: hrsfansretreat
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index.html
    login: required
    secure: always

  - url: /static/([^/]*\.(css|js|png))
    static_files: static/\1
    upload: static/[^/]*\.(css|js|png)
    secure: always

  - url: /call/admin/[^/]*
    script: main.application
    login: admin
    auth_fail_action: unauthorized
    secure: always

  - url: /call/[^/]*
    script: main.application
    login: required
    auth_fail_action: unauthorized
    secure: always

skip_files:
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?\..*
  - ^(.*/)?.*\.coffee
  - ^(.*/)?.*\.md
  - ^LICENSE

libraries:
  - name: yaml
    version: "3.10"
